---
- name: 'install'
  yum: 
   name: 
     - MySQL-python
     - mariadb-server
  state: present

- name: 'restart'
  service: name=mariadb state=restarted enabled=yes
  
- name: 'root password reset'
  ignore_errors: yes
  mysql_user:
       login_user: root
       login_password: ''
       name: root
       password: "{{mysql_root}}"
       host_all: yes
 
- name: 'anonymous'
  mysql_user:
       login_user: root
       login_password: "{{mysql_root}}"
       name: ''
       state: absent
       host_all: yes

- name: 'add db'
  mysql_db:
       login_user: root
       login_password: "{{mysql_root}}"
       name: "{{mysql_db}}"
       state: present
      
- name: 'priv'
  mysql_user:
       login_user: root
       login_password: "{{mysql_root}}"
       name: "{{mysql_user}}"
       password: "{{mysql_password}}"
       state: present
       host: localhost
       priv: "{{mysql_db}}.*:ALL"
